import type { GalleryItem, GalleryPage } from "./types";

/**
 * Gallery page. Two named sections — "Property" (the house itself) and
 * "Sense of Place" (the island, the light, the people). Each section gets
 * its own masonry grid, so each also gets its own lightbox sequence.
 *
 * Add a photograph by dropping a JPG into /public/images and pushing an
 * `img(slug, alt, width, height)` entry; add a film by dropping an .mp4
 * into /public/videos plus a poster into /public/images/posters and
 * pushing a `film(slug, caption, width, height)` entry.
 */

const img = (slug: string, alt: string, width: number, height: number): GalleryItem => ({
  type: "image",
  image: { src: `/images/${slug}.jpg`, alt, width, height },
});

const film = (slug: string, caption: string, width = 1080, height = 1920): GalleryItem => ({
  type: "video",
  video: {
    src: `/videos/${slug}.mp4`,
    poster: { src: `/images/posters/${slug}.jpg`, alt: `${caption} — still from the film`, width, height },
  },
  caption,
});

export const gallery: GalleryPage = {
  hero: {
    image: { src: "/images/gallery-pool-sea.jpg", alt: "Pool and the Aegean at dusk", width: 2400, height: 1600, position: "50% 60%" },
    mobileImage: { src: "/images/gallery-sunbeds.jpg", alt: "Deck chairs above the sea", width: 1600, height: 2400, position: "50% 50%" },
  },
  intro: { eyebrow: "GALLERY", heading: "The House and the Island" },
  featured: {
    type: "video",
    video: {
      src: "/videos/villa-film.mp4",
      poster: { src: "/images/posters/villa-film.jpg", alt: "Beachfront Villa Mykonos — the film", width: 1920, height: 1080 },
    },
    caption: "Beachfront Villa Mykonos — the film",
  },
  sections: [
    {
      id: "property",
      title: "Property",
      items: [
        img("001-drone-2", "Aerial view of the villa and its pool set into the rocky headland", 1821, 1365),
        img("007-uppergate-mainentrance", "The upper gate at the main entrance, a tall clay urn beside the door and the sea beyond", 2048, 1365),
        img("dscf0194", "A guest diving into the pool", 1364, 2048),
        img("entance-1", "The entrance hall, antique urns set on dark timber blocks", 2048, 1536),
        img("026-masterbedroom-upperlevel", "The master bedroom on the upper level, glazed doors open onto its terrace", 2048, 1365),
        img("living-room", "The living room and dining table in afternoon light", 2048, 1536),
        img("065-guesthouse-2-lowerlevel", "The guest house bedroom with its arched dressing area", 1364, 2048),
        img("081-swimmingpool", "The pool set above the bay, the sea filling the horizon", 2048, 1365),
        film("reel-11-breakfast", "Breakfast on the terrace"),
        img("dji-0342", "Aerial panorama of the property strung along the coastline", 2048, 1148),
        img("122-terrace-groundlevel", "The outdoor kitchen and bar on the ground-level terrace, built around an olive tree", 2047, 1365),
        img("dscf0665", "Guests on the loungers beside the pool in the late afternoon", 1364, 2048),
        img("002-drone", "Aerial view straight down over the pool, loungers and pergola", 1821, 1365),
        img("professional-kitchen", "The professional kitchen in pale timber", 2048, 1536),
        img("031-masterbedroom-upperlevel", "Teak armchairs on the master bedroom terrace, facing the open sea", 2048, 1365),
        img("105-terrace-privatebeachlevel", "Thatched parasols and loungers on the terrace above the private beach", 2048, 1365),
        img("138-wellness", "Folded towels and ceramics on the wellness room shelves", 1364, 2048),
        film("reel-2-pool", "The heated pool"),
        img("jsph2109", "The open kitchen island with stools and woven pendant lights", 2048, 1536),
        img("036-bedroom-2-lowerlevel", "The second bedroom on the lower level, opening through to the garden", 2047, 1365),
        img("097-terrace-swimmingpool", "The long dining table on the shaded terrace beside the pool", 2048, 1365),
        img("amenities-minibar", "The minibar shelves with coffee machine, books and ceramics", 1364, 2048),
        img("003-drone", "Aerial view of the shoreline, terraces and the beach below the villa", 1821, 1365),
        img("living-room-2", "Deep linen sofas and a low table in the living room", 2048, 1536),
        img("tama-43", "The pool and thatched parasols above the bay in the afternoon", 3840, 2560),
        img("085-swimmingpool", "A guest reading under a straw parasol above the pool", 1364, 2048),
        film("reel-4-living-room", "The living room"),
        img("034-masterbedroom-upperlevel", "Twin basins and round mirrors in the master bathroom", 2048, 1365),
        img("123-terrace-groundlevel", "The outdoor kitchen's range and stone counter under the timber roof", 2047, 1365),
        img("upper-terrace", "Teak armchairs on the upper terrace between whitewashed walls", 2048, 1536),
        img("dscf0770", "A guest watching the sun set from the bedroom window", 1364, 2048),
        img("083-swimmingpool", "Sunset over the sea from the edge of the pool", 2048, 1365),
        img("039-bedroom-3-lowerlevel", "The third bedroom on the lower level, doors open to the terrace", 2048, 1365),
        img("jsph2239", "The indoor dining table laid under two woven globe lamps", 2048, 1536),
        img("dscf1682-edit", "Guests talking beside the pool at sunset", 1364, 2048),
        film("reel-3-massage", "The massage room"),
        img("dji-0345", "Aerial panorama of the garden terraces above the cove", 2048, 1148),
        img("132-terrace-groundlevel", "The covered lounge on the ground-level terrace, stone wall behind a long banquette", 2047, 1365),
        img("amenities-cinema", "The cinema room, screen lit and sofas drawn up to it", 2048, 1536),
        img("106-terrace-privatebeachlevel", "Loungers under straw parasols looking over the rocky shoreline", 2048, 1365),
        img("066-guesthouse-2-lowerlevel", "Open shelving and coffee station in the guest house", 1364, 2048),
        img("009-dsc-0425-pool-view", "The pool and pool house above the turquoise bay", 2048, 1366),
        img("047-bedroom-4-lowerlevel", "The fourth bedroom on the lower level, bed facing the garden doors", 2048, 1365),
        img("ground-level", "Ground-level living area with pale plaster walls and timber columns", 2048, 1536),
        film("reel-10-dinner", "Dinner service"),
        img("dscf0950", "A guest at the window, looking out to the sea in the early light", 1364, 2048),
        img("141-wellness", "Loungers on the stone terrace outside the wellness rooms", 2048, 1365),
        img("upper-guestbedroom", "Light falling across the bed in the upper guest bedroom", 2048, 1536),
        img("004-drone", "Aerial view of the property above its own cove", 1821, 1365),
        img("110-privatebeach", "The private beach and swimming platform among white rocks", 2048, 1365),
        img("139-wellness", "The massage table in the quiet treatment room", 1364, 2048),
        img("professional-kitchen-2", "Work surfaces and appliances along the professional kitchen", 2048, 1536),
        img("048-bedroom-4-lowerlevel", "The fourth bedroom's built-in bed and dressing area", 2048, 1365),
        film("reel-14-terrace", "The terrace at golden hour"),
        img("tama-91", "The dining room at dusk, lit by woven pendant lamps", 3840, 2560),
        img("dscf0649", "A guest on the whitewashed roof terrace, framed by olive branches", 1364, 2048),
        img("dining-outdoor-kitchen-pool-area", "The outdoor kitchen and dining area beside the pool", 2048, 1536),
        img("094-swimmingpool", "The long pool running towards the pool house and the sea", 2048, 1365),
        img("075-bedroomsterrace-lowerlevel", "The lower-level bedroom terrace, screened by greenery above the sea", 2048, 1365),
        img("dscf1722-edit", "Two guests on the terrace looking out over the water", 1364, 2048),
        img("jsph2269", "The outdoor kitchen and bar beside the pool", 2048, 1536),
        img("137-wellness", "The softly lit treatment room in the wellness area", 2047, 1365),
        film("reel-6-pool", "Evening by the pool"),
        img("008-uppergate-mainentrance", "The whitewashed entrance building seen from the drive, sea in the distance", 2048, 1365),
        img("dscf1544", "Two guests watching the sun go down over the sea", 1362, 2048),
        img("swimming-pool-area", "The pool, loungers and parasols above the bay", 2048, 1536),
        img("054-bedroom-5-lowerlevel", "The fifth bedroom on the lower level, white and simply furnished", 2048, 1365),
        img("dji-0348", "Aerial panorama of the pool and the rocky shore below", 2048, 1148),
        img("living-room-evening", "The living room in the evening, lamps lit and curtains drawn back", 2048, 1536),
        img("107-terrace-privatebeachlevel", "Cushioned daybed under the thatched roof at beach level", 2048, 1365),
        img("amenities-gym", "The gym, equipment facing the windows and the light", 3840, 2880),
        film("reel-1-gym", "The indoor gym"),
        img("upper-guestbedroom-1", "The upper guest bedroom's built-in wardrobes and pendant light", 2048, 1536),
        img("099-terrace-swimmingpool", "The pool house and terrace seen across the water of the pool", 2048, 1365),
        img("tama-37", "Evening light through the dining room doors onto the terrace", 2048, 1364),
        img("entrance-3", "Rustic wooden benches and clay urns in the entrance hall", 2048, 1536),
        img("076-bedroomsterrace-lowerlevel", "Dry-stone walls and granite boulders beside the bedroom terrace", 2048, 1365),
        img("professional-kitchen-3", "Ovens and range in the professional kitchen", 2048, 1536),
        img("009-dsc-0425-pool-view-2", "The pool terrace and pergola seen from above the bay", 2048, 1366),
        img("living-room-1", "The dining table and armchairs in the living room", 2048, 1536),
        film("reel-5-cinema-room", "The cinema room"),
        img("142-landscape", "The path down through the garden to the sea", 2047, 1365),
        img("ground-level-1", "The ground-level kitchen island and stools under the beamed ceiling", 2048, 1536),
        img("tama-77", "Dusk over the sea and the lit pool", 2048, 1364),
        img("jsph2504", "The cinema room with the projection screen lit", 2048, 1536),
        img("villa-tama-45", "A seafood course plated and set on a wooden table", 3840, 2560),
        img("upper-terrace-3", "The upper terrace and pergola with the sea beyond", 2048, 1536),
        img("dscf0131-edit", "Teak armchairs on the terrace looking across the sea", 2048, 1364),
        img("dining-outdoor-kitchen-pool-area-2", "The long dining table under the outdoor kitchen's timber roof", 2048, 1536),
      ],
    },
    {
      id: "sense-of-place",
      title: "Sense of Place",
      items: [
        film("place-1-sea", "The open sea", 1920, 1080),
        img("tama-4", "The pool house and the bay at first light", 1364, 2048),
        img("dscf0094", "Parasols and loungers around the pool above the bay", 2048, 1364),
        film("reel-13-single-drone-1", "Drone flight over the villa"),
        img("villa-tama-030", "A guest in a Tama robe, seen from behind", 1364, 2048),
        img("tama-48", "A guest silhouetted against the sun setting beyond the pool", 1364, 2048),
        film("reel-7-beach-1", "The private beach"),
        img("dscf9101", "The pool house and loungers above the bay at midday", 2048, 1152),
        img("villa-tama-23", "Guests gathered around the kitchen island in the morning", 1364, 2048),
        img("villa-tama-181", "The chef laying out a spread of mezze and fruit", 1364, 2048),
        img("tama-30", "Charred vegetables on a board, ready to serve", 1364, 2048),
        film("place-2-garden", "The garden paths", 1920, 1080),
        img("dscf3860", "Guests walking down the stone path through the garden to the sea", 1364, 2048),
        img("villa-tama-27", "A guest sitting on the bed, framed by the open doorway onto the sea", 2048, 1364),
        img("villa-tama-31", "Guests sitting at the edge of the pool above the bay", 1364, 2048),
        img("tama-33", "A bowl of branches under a woven pendant, the sea through the window", 1520, 2048),
        img("tama-52", "The living room at dusk, wooden dining table and low sofas facing the bay", 1364, 2048),
        img("dscf9597", "A bedroom in soft morning light, the bed turned down", 2048, 1152),
        img("villa-tama-060", "Cut flowers on the console beside the bed", 1364, 2048),
        img("dscf4078", "A guest reading in a deck chair on the beach", 1364, 2048),
        film("reel-walking-to-beach", "Walking down to the beach"),
        img("villa-tama-33", "Clear water over pale rocks in the cove", 1364, 2048),
        img("dscf4016", "White rocks and shallow clear water at the shoreline", 2048, 1364),
        film("reel-9-balcony", "Balcony at golden hour"),
        img("tama-10", "Cane armchairs in a warmly lit corner of the house", 1402, 2048),
        img("villa-tama-151", "A tray of baking coming out of the oven", 1364, 2048),
        film("place-3-sunset", "Sunset over the Aegean", 1920, 1080),
        img("tama-60", "The sun dropping into the sea beyond the terrace", 1364, 2048),
        img("dscf9016", "The pool terrace and loungers seen from the hillside above", 1344, 2048),
        img("villa-tama-42", "A seafood starter plated along a narrow dish", 1364, 2048),
        img("tama-85", "The dining table laid for dinner beside the stone wall", 1364, 2048),
        img("dscf3830", "The covered lounge, stone wall behind deep sofas", 1364, 2048),
        img("tama-37", "Evening light through the dining room doors onto the terrace", 2048, 1364),
        img("villa-tama-16", "Guests beside the lit pool after dark", 1364, 2048),
        img("tama-26", "Two low stools in a shaft of sunlight against a white wall", 1364, 2048),
        film("reel-15-single-drone-3", "Drone view of the coastline"),
        img("villa-tama-082", "A Tama towel folded on a lounger by the pool", 1364, 2048),
        img("dscf9393", "The dining room lit by a single woven pendant", 1152, 2048),
        img("villa-tama-13", "A deck chair on the terrace in the afternoon sun", 1364, 2048),
        img("tama-32", "The pool and terraces seen from the hillside above the sea", 1364, 2048),
        film("place-4-shore", "The shoreline below the villa", 1920, 1080),
        img("villa-tama-32", "A guest standing among wildflowers on the rocky shore", 1364, 2048),
        img("dscf9318", "A long, bare room opening onto the sea through glazed doors", 2048, 1152),
        film("reel-8-beach-2", "Down at the beach"),
        img("tama-49", "Evening light over the pool and the bay beyond", 1364, 2048),
        img("villa-tama-44", "A row of canapés along a wooden board", 1364, 2048),
        img("dscf3929", "The pool house and loungers with the bay beyond", 1364, 2048),
        img("tama-7", "A lamp-lit corridor at night, sea light at the far end", 1392, 2048),
        film("reel-12-balcony-2", "Morning on the balcony"),
        img("villa-tama-35", "Guests sitting on the pool edge looking out to the bay", 1364, 2048),
        img("tama-77", "Dusk over the sea and the lit pool", 2048, 1364),
        film("reel-16-single-drone-4", "Drone view over the headland"),
        img("villa-tama-188", "Canapés plated along a long white dish", 1364, 2048),
        img("tama-82", "The sea seen over the parapet from a shaded room", 1536, 2048),
        film("reel-17-single-drone-5", "Drone view of the bay"),
        img("villa-tama-2", "The living and dining room with woven pendants and doors open to the garden", 2560, 3840),
        img("dscf9463", "The sea and the pool seen from the upper terrace", 1152, 2048),
        film("reel-18-single-drone-6", "Drone view at sunset"),
      ],
    },
  ],
};
